_wandb:
    value:
        cli_version: 0.25.0
        e:
            4y5yt7nyu95ii8uy0n65a80cv46pj62a:
                args:
                    - --config=/cosmos_storage/home/diegovillalba/JaxPM/pm2nbody/configs/cnn_wst_J2_L4.yaml
                codePath: pm2nbody/train_refactored_new.py
                codePathLocal: train_refactored_new.py
                cpu_count: 192
                cpu_count_logical: 192
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "972240457728"
                        used: "175947956224"
                email: villalbagonzalezdiegoantonio@gmail.com
                executable: /cosmos_storage/home/diegovillalba/JaxPM/.venv/bin/python
                git:
                    commit: 4387bf434746cb8438ff02a2761711ea1c470bb2
                    remote: git@github.com:DiegoViillalba/JaxPM.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-86664913-d38d-6dd8-b5b4-160e965dcee0
                host: cosmos-node.sw.ehu.es
                memory:
                    total: "3245931581440"
                os: Linux-5.14.0-611.30.1.el9_7.x86_64-x86_64-with-glibc2.34
                program: /cosmos_storage/home/diegovillalba/JaxPM/pm2nbody/train_refactored_new.py
                python: CPython 3.11.14
                root: /cosmos_storage/home/diegovillalba/JaxPM/models
                startedAt: "2026-03-26T05:11:43.914853Z"
                writerId: 4y5yt7nyu95ii8uy0n65a80cv46pj62a
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 2
                - 16
                - 61
            "4": 3.11.14
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
correction_model:
    value:
        add_particle_velocities: true
        channels_hidden_dim: 32
        embed_globals: false
        global_conditioning: add
        globals_embedding_dim: 64
        input_dim: 1
        kernel_size: 3
        latent_size: 64
        n_convolutions: 3
        n_fully_connected: 2
        n_globals_embedding: 1
        n_knots: 16
        pad_periodic: true
        type: cnn_wst
        use_attention_interpolation: false
        wst_J: 3
        wst_L: 4
data:
    value:
        box_size: 256
        mesh_hr: 256
        mesh_lr: 128
        n_particles: 128
        n_snapshots: 50
        n_test_sims: 1
        n_train_sims: 1
        n_val_sims: 1
        snapshots: null
training:
    value:
        batch_size: 1
        checkpoint_every: 10
        fractional_mse: false
        lambda_cross_corr: 0
        lambda_density: 0
        lambda_pk: 0
        lambda_pos: 1
        lambda_velocity: 1
        log_pos: false
        loss: mse_positions
        max_idx: 49
        n_steps: 60
        patience: 15
        sample_snapshots: false
        schedule:
            factor: 0.5
            initial_lr: 0
            min_lr: 5e-05
            n_steps: 60
            patience: 5
            peak_value: 0.0004
            type: cosine
            warmup_steps: 5
        seed: 0
        weight_decay: 0.0001
        weight_snapshots: true
wandb:
    value:
        project: pm2nbody
