data:
  mesh_lr: 128
  mesh_hr: 256
  n_train_sims: 1
  n_val_sims: 1
  snapshots: null
  box_size: 256.0
  n_snapshots: 50
  n_particles: 128
correction_model:
  type: cnn
  channels_hidden_dim: 16
  n_convolutions: 3
  n_fully_connected: 2
  input_dim: 1
  kernel_size: 3
  pad_periodic: true
  embed_globals: false
  n_globals_embedding: 1
  globals_embedding_dim: 64
  global_conditioning: add
  use_attention_interpolation: false
  add_particle_velocities: true
  n_knots: 16
  latent_size: 64
training:
  seed: 0
  n_steps: 10
  batch_size: 1
  patience: 20
  checkpoint_every: 5
  sample_snapshots: true
  loss: mse_positions
  weight_snapshots: true
  lambda_pos: 1.0
  lambda_velocity: 1.0
  lambda_density: 0.0
  lambda_pk: 0.0
  lambda_cross_corr: 0.0
  log_pos: false
  fractional_mse: false
  weight_decay: 0.0001
  schedule:
    type: cosine
    initial_lr: 0.0
    peak_value: 0.0003
    warmup_steps: 500
    n_steps: 20000
    factor: 0.5
    patience: 5
    min_lr: 1.0e-06
wandb:
  project: pm2nbody
